# Generated by Django 5.1.7 on 2025-03-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('incident_type', models.CharField(choices=[('Harassment', 'Harassment'), ('Stalking', 'Stalking'), ('Theft', 'Theft'), ('Assault', 'Assault'), ('Suspicious Activity', 'Suspicious Activity'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
